---
- name: Deploy Application to Kubernetes Server
  hosts: kube_servers
  become: yes
  tasks:
    - name: Copy shell script to Kubernetes server
      copy:
        src: ../scripts/shell-script.sh
        dest: /tmp/shell-script.sh
        mode: '0755'

    - name: Execute the shell script with dynamic variables
      command: "/tmp/shell-script.sh {{ app_name }} {{ app_version }}"

