---
- name: Create Repo with Group in Git Cloudinator
  hosts: kube_servers
  become: yes
  # vars_files:
  #   - ../vars/app_vars.yml
  tasks:
    - name: Copy shell script to Kubernetes server
      copy:
        src: ../scripts/deploy-k8s.sh
        dest: /root/istad/deploy-k8s.sh
        mode: '0755'

    - name: Execute the shell script with dynamic variables
      command: "bash /root/istad/deploy-k8s.sh {{ APP_NAME }}  {{IMAGE}} {{ NAMESPACE }} {{ FILE_Path }}"
